<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DarkSkies.Gui</AssemblyName>
    <RootNamespace>DarkSkies.Gui</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <PathMap>$(MSBuildThisFileDirectory)=/_/gui/</PathMap>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DarkSkies.Core\DarkSkies.Core.csproj" />
  </ItemGroup>
</Project>
